/*
This file is part of Wow Log Parser, a program to parse World of Warcraft combat log files.
Copyright (C) Gustav Haapalahti

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/

package wowlogparser.gui;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.prefs.Preferences;
import wowlogparserbase.EventCollection;
import wowlogparserbase.EventCollectionSimple;

/**
 *
 * @author  racy
 */
public class EventsPlotFrame extends javax.swing.JFrame {

    /** Creates new form EventsPlotFrame */
    public EventsPlotFrame(EventCollectionSimple ec, Preferences basePrefs) {
        initComponents();
        eventsPlotPanel1.setPrefsRoot(basePrefs);
        eventsPlotPanel1.setEvents(ec);
        addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                eventsPlotPanel1.saveCheckStates();
                super.windowClosing(e);
            }
            
        });
        pack();
    }

    public EventsPlotFrame(EventCollection timeReferenceCollection, EventCollectionSimple ec, Preferences basePrefs) {
        initComponents();
        eventsPlotPanel1.setPrefsRoot(basePrefs);
        eventsPlotPanel1.setEvents(timeReferenceCollection, ec);
        addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                eventsPlotPanel1.saveCheckStates();
                super.windowClosing(e);
            }

        });
        pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventsPlotPanel1 = new wowlogparser.gui.EventsPlotPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        eventsPlotPanel1.setName("eventsPlotPanel1"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(eventsPlotPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(eventsPlotPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private wowlogparser.gui.EventsPlotPanel eventsPlotPanel1;
    // End of variables declaration//GEN-END:variables

}
